notifications:
  enabled: true
  diia:
    url: localhost:5000
    partner:
      token: partnerToken

data-platform:
  kafka:
    bootstrap: localhost:9092
    topic-properties:
      creation:
        num-partitions: 1
        replication-factor: 1
    ssl:
      enabled: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: username
    password: password

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
  mail:
    host: localhost
    port: 3025
    username: username
    password: password
    protocol: smtp

user-settings-service:
  url: http://localhost:8878

keycloak:
  url: http://localhost:8200
  system-user:
    realm: test-realm
    client-id: client-id
    client-secret: client-secret

audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false