notifications:
  enabled: true

data-platform:
  kafka:
    enabled: ${notifications.enabled}
    consumer:
      enabled: true
      group-id: notifications-service
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      trusted-packages:
        - com.epam.digital.data.platform.notification.dto
        - com.epam.digital.data.platform.notification.dto.email
        - com.epam.digital.data.platform.notification.dto.inbox
        - com.epam.digital.data.platform.notification.dto.diia
      error-handler:
        enabled-dlq: true
      custom-config:
        "[retry.backoff.ms]": 10000
        "[spring.deserializer.key.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[isolation.level]": read_committed
    producer:
      enabled: true
    topics:
      user-notifications: user-notifications
      email-notifications: email-notifications
      inbox-notifications: inbox-notifications
      diia-notifications: diia-notifications
    topic-properties:
      creation:
        enabled: true
        enabled-dlq: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  zipkin:
    baseUrl: http://zipkin.istio-system.svc:9411
    sender:
      type: web
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true
      remote-fields: x-request-id
      correlation-fields: x-request-id
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=2h

management:
  endpoints:
    web:
      exposure:
        include: 'health'
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState, db, webServices
    loggers:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    kafka:
      enabled: false
    kubernetes:
      enabled: false
    webservices:
      readiness:
        services:
          - ${user-settings-service.url}/actuator/health
          - ${keycloak.url}

recipients-processing:
  recipients-max-thread-pool-size: 10
  channels-max-thread-pool-size: 5