notifications:
  enabled: false

external-systems:
  diia:
    url: localhost:5000
    auth:
      secret:
        token: partnerToken

user-settings-service:
  url: http://localhost:8300

keycloak:
  url: http://localhost:8200
  citizen-user:
    realm: citizenUserRealm
    client-id: citizenUserClientId
    client-secret: citizenUserClientSecret
  officer-user:
    realm: officerUserRealm
    client-id: officerUserClientId
    client-secret: officerUserClientSecret

audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false
      
data-platform:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres
  kafka:
    bootstrap: localhost:9092
    topic-properties:
      creation:
        num-partitions: 1
        replication-factor: 1
    ssl:
      enabled: false