notifications:
  enabled: true

data-platform:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: username
    password: password

spring:
  application:
    name: ddm-notification-service-inbox
  jpa:
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver

audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false

keycloak:
  url: http://localhost:8200
  citizen-user:
    realm: citizen-realm
    client-id: citizen-client-id
    client-secret: citizen-client-secret
  officer-user:
    realm: officer-realm
    client-id: officer-client-id
    client-secret: officer-client-secret
