{{- if or (not .Values.global.excludePortals) (not (has "citizen" .Values.global.excludePortals)) }}
{{- if .Values.configWatcher.deploy -}}
apiVersion: v1
kind: Service
metadata:
  name: notification-service-channel-configuration
  labels:
    {{- include "ddm-notification-service.configWatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ddm-notification-service.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}