{{- if .Values.configWatcher.deploy -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ include "ddm-notification-service.configWatcher.serviceAccountName" . }}
roleRef:
    kind: Role
    name: {{ include "ddm-notification-service.configWatcher.serviceAccountName" . }}-role
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: {{ include "ddm-notification-service.configWatcher.serviceAccountName" . }}
{{- end }}
