{{- if .Values.global.notifications.diia }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.diia.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    spring.cloud.kubernetes.config: 'true'
data:
  application.yaml: |-
    notifications:
      diia:
        url: {{ .Values.global.notifications.diia.url }}
{{- end }}