{{- $diiaSecret := (lookup "v1" "Secret" .Values.namespace "diia-secret") }}
  {{- if not $diiaSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.diiaMockSecret }}
type: Opaque
data:
  external-systems.diia.auth.secret.token: ""
  {{- end }}