{{- if .Values.global.notifications.diia }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.diia.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    spring.cloud.kubernetes.secret: 'true'
data:
  notifications.diia.partner.token: {{ .Values.global.notifications.diia.partner.token | b64enc }}
{{- end }}