{{- if .Values.global.registry.ddmNotificationService.hpa.enabled }}
{{- if or (not .Values.global.excludePortals) (not (has "citizen" .Values.global.excludePortals)) }}
apiVersion: {{ include "horizontalPodAutoscaler.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ddm-notification-service.fullname" . }}
  labels:
    {{- include "ddm-notification-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ddm-notification-service.fullname" . }}
  minReplicas: {{ .Values.global.registry.ddmNotificationService.hpa.minReplicas }}
  maxReplicas: {{ .Values.global.registry.ddmNotificationService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
{{- end }}
{{- end }}
