{{ if .Values.framework }}
{{ if eq .Values.framework "operator-sdk" }}
{{- if or (not .Values.global.excludePortals) (not (has "citizen" .Values.global.excludePortals)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: edp-{{ include "ddm-notification-service.serviceAccountName" . }}-role
rules:
    - apiGroups:
          - ""
      resources:
          - configmaps
          - pods
      verbs:
          - create
          - get
          - list
          - delete
{{- end }}
{{ end }}
{{ end }}
