notifications:
  enabled: true

data-platform:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: username
    password: password

spring:
  application:
    name: ddm-notification-service-core
  jpa:
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver

audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false
