notifications:
  enabled: true

external-systems:
  diia:
    url: http://localhost:9561
    auth:
      secret:
        token: partnerToken

data-platform:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: username
    password: password

spring:
  application:
    name: ddm-notification-service-diia
  jpa:
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=2h

audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false